// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { type OtpApiError, useOtpFlow } from "@k-otp/sdk/vue";
import { computed, ref } from "vue";

defineProps<{ mock: boolean }>();

const phoneNumber = ref("");
const code = ref("");
const {
  send,
  verify,
  reset,
  issueId,
  verified,
  reasonCode,
  attemptsRemaining,
  error,
  sending,
  verifying,
  idempotencyKey,
  canSend,
  canVerify,
  cooldownRemainingMs,
} = useOtpFlow({ resendCooldownMs: 30_000, idempotencyKeyPrefix: "signup" });

const seconds = computed(() => Math.ceil(cooldownRemainingMs.value / 1000));
const sendLabel = computed(() => {
  if (sending.value) return "Sending...";
  if (seconds.value > 0) return `Resend in ${seconds.value}s`;
  if (idempotencyKey.value) return "Retry";
  return issueId.value ? "Resend code" : "Send code";
});

const describeError = (e: OtpApiError): string => {
  switch (e.code) {
    case "PAYMENT_REQUIRED":
      return "The service is temporarily unable to send codes. Please try again later.";
    case "TOO_MANY_REQUESTS":
      return `Too many attempts. Try again in ${Math.ceil((e.retryAfterMs ?? 0) / 1000)}s.`;
    case "FORBIDDEN":
      return "This page's origin is not allowed for the public key (check allowedOrigins).";
    case "TIMEOUT":
    case "NETWORK_ERROR":
    case "SERVICE_UNAVAILABLE":
    case "INTERNAL_SERVER_ERROR":
      return "We could not confirm the code was sent. Retrying is safe.";
    default:
      return "Something went wrong. Please try again.";
  }
};

const onSend = () => send({ phoneNumber: phoneNumber.value, purpose: "signup" });
const onVerify = () => verify(code.value);
</script>

<template>
  <main v-if="verified">
    <h1>Verified</h1>
    <button type="button" @click="reset">Start over</button>
  </main>
  <main v-else>
    <h1>Phone verification</h1>
    <p v-if="mock">Mock mode: no API key configured, the code is 123456.</p>

    <form @submit.prevent="onSend">
      <label>
        Phone number
        <input v-model="phoneNumber" inputmode="tel" placeholder="01012345678" required />
      </label>
      <button type="submit" :disabled="!canSend">{{ sendLabel }}</button>
    </form>

    <form v-if="issueId" @submit.prevent="onVerify">
      <label>
        Code
        <input
          v-model="code"
          inputmode="numeric"
          autocomplete="one-time-code"
          maxlength="6"
          required
        />
      </label>
      <button type="submit" :disabled="!canVerify">
        {{ verifying ? "Checking..." : "Verify" }}
      </button>
    </form>

    <p v-if="reasonCode === 'MISMATCH'">Wrong code, {{ attemptsRemaining }} attempts left.</p>
    <p v-else-if="reasonCode">
      This code can no longer be used ({{ reasonCode }}). Request a new one.
    </p>
    <p v-if="error" role="alert">{{ describeError(error) }}</p>
  </main>
</template>

// examples/svelte-vite/src/App.svelte
<script lang="ts">
  import { createOtpStores, type OtpApiError, otpForm } from "@k-otp/sdk/svelte";
  import { onDestroy } from "svelte";
  import { mockFetch } from "./mock-fetch";

  const apiKey = import.meta.env.VITE_K_OTP_PUBLIC_KEY?.trim();
  const baseUrl = import.meta.env.VITE_K_OTP_BASE_URL?.trim() || undefined;
  const mock = !apiKey;

  // Stores are created per component instance: nothing is shared globally.
  const otp = createOtpStores(
    apiKey
      ? { apiKey, baseUrl }
      : // No key configured: talk to the in-browser mock API.
        { apiKey: "pk_mock", fetch: mockFetch },
  );
  const flow = otp.createFlow({ resendCooldownMs: 30_000, idempotencyKeyPrefix: "signup" });
  onDestroy(() => flow.abort());

  const describeError = (e: OtpApiError): string => {
    switch (e.code) {
      case "PAYMENT_REQUIRED":
        return "The service is temporarily unable to send codes. Please try again later.";
      case "TOO_MANY_REQUESTS":
        return `Too many attempts. Try again in ${Math.ceil((e.retryAfterMs ?? 0) / 1000)}s.`;
      case "FORBIDDEN":
        return "This page's origin is not allowed for the public key (check allowedOrigins).";
      case "TIMEOUT":
      case "NETWORK_ERROR":
      case "SERVICE_UNAVAILABLE":
      case "INTERNAL_SERVER_ERROR":
        return "We could not confirm the code was sent. Retrying is safe.";
      default:
        return "Something went wrong. Please try again.";
    }
  };

  const onSend = (data: FormData) =>
    flow.send({ phoneNumber: String(data.get("phoneNumber") ?? ""), purpose: "signup" });
  const onVerify = (data: FormData) => flow.verify(String(data.get("code") ?? ""));

  const seconds = $derived(Math.ceil($flow.cooldownRemainingMs / 1000));
  const sendLabel = $derived(
    $flow.issueState.isLoading
      ? "Sending..."
      : seconds > 0
        ? `Resend in ${seconds}s`
        : $flow.idempotencyKey
          ? "Retry"
          : $flow.issueId
            ? "Resend code"
            : "Send code",
  );
</script>

{#if $flow.verified}
  <main>
    <h1>Verified</h1>
    <button type="button" onclick={flow.reset}>Start over</button>
  </main>
{:else}
  <main>
    <h1>Phone verification</h1>
    {#if mock}<p>Mock mode: no API key configured, the code is 123456.</p>{/if}

    <form use:otpForm={onSend}>
      <label>
        Phone number
        <input name="phoneNumber" inputmode="tel" placeholder="01012345678" required />
      </label>
      <button type="submit" disabled={!$flow.canSend}>{sendLabel}</button>
    </form>

    {#if $flow.issueId}
      <form use:otpForm={onVerify}>
        <label>
          Code
          <input name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" required />
        </label>
        <button type="submit" disabled={!$flow.canVerify}>
          {$flow.verifyState.isLoading ? "Checking..." : "Verify"}
        </button>
      </form>
    {/if}

    {#if $flow.reasonCode === "MISMATCH"}
      <p>Wrong code, {$flow.attemptsRemaining} attempts left.</p>
    {:else if $flow.reasonCode}
      <p>This code can no longer be used ({$flow.reasonCode}). Request a new one.</p>
    {/if}
    {#if $flow.error}<p role="alert">{describeError($flow.error)}</p>{/if}
  </main>
{/if}
